services:
  wiki_chatbot:
    build:
      context: .
      dockerfile: Dockerfile.chatbot
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - REPO_OWNER=${REPO_OWNER}
        - REPO_NAME=${REPO_NAME}
        - CHATBOT_PORT=${CHATBOT_PORT}
        - WORKERS=${WORKERS}
    ports:
      - "${CHATBOT_PORT}:${CHATBOT_PORT}"
    environment:
      - RESOURCES_PATH=${RESOURCES_PATH}
      - CHATBOT_PORT=${CHATBOT_PORT}
      - REPO_NAME=${REPO_NAME}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - REPO_OWNER=${REPO_OWNER}
      - DB_PATH=${DB_PATH}
      - COLLECTION_NAME=${COLLECTION_NAME}
      - EMBEDDING_NAME=${EMBEDDING_NAME}
      - LLM_NAME=${LLM_NAME}
      - MAX_BATCH_SIZE=${MAX_BATCH_SIZE}
      - CHUNK_SIZE=${CHUNK_SIZE}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP}
      - PROMPT=${PROMPT}
      - WORKERS=${WORKERS}
    env_file:
      - ./chatbot/code/.env
    volumes:
      - ./chatbot:/app  # Monta el código de tu proyecto en el contenedor
    depends_on:
      - redis  # Asegura que Redis se inicie antes que el chatbot
    restart: unless-stopped

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 20 1 --loglevel warning
    restart: unless-stopped

volumes:
  redis_data:
    driver: local