# Establecer la imagen base
FROM python:3.10

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Instalar dependencias
RUN apt update && apt install -y git

# Agregar las credenciales con variables de entorno
ARG GITHUB_TOKEN
RUN git clone https://${GITHUB_TOKEN}@github.com/usuario/repo.git /app/repo

# Copiar solo el archivo de requerimientos antes del resto del código
COPY requirements.txt /app/requirements.txt

# Instalar dependencias ANTES de copiar el resto de archivos
RUN pip install --no-cache-dir -r requirements.txt

# Copiar los archivos de la aplicación al contenedor
COPY . /app

# Exponer el puerto de la aplicación
EXPOSE 5000

# Comando para ejecutar la aplicación
CMD ["python", "wiki_repo_webhook_server.py"]