# Establecer la imagen base
FROM python:3.10

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Instalar curl y otras herramientas necesarias
RUN apt update && apt install -y curl

# Instalar Ollama
RUN curl -fsSL https://ollama.com/install.sh | sh

# Copiar los archivos de la aplicación al contenedor
COPY . /app

# Instalar las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Exponer el puerto de la aplicación
EXPOSE 6000

# Comando para ejecutar la aplicación
CMD ["python", "wiki_chatbot_server.py"]