services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile.chatbot
      args:
        - LLM_NAME=${LLM_NAME}
        - CHATBOT_PORT=${CHATBOT_PORT}
        - WORKERS=${WORKERS}
        - REDIS_PORT=${REDIS_PORT}
    ports:
      - "${CHATBOT_PORT}:${CHATBOT_PORT}"
    environment:
      - LLM_NAME=${LLM_NAME}
      - CHATBOT_PORT=${CHATBOT_PORT}
      - WORKERS=${WORKERS}
      - REDIS_PORT=${REDIS_PORT}
    env_file:
      - ./chatbot/code/.env
    volumes:
      - ./chatbot:/app
