# Establecer la imagen base
FROM python:3.10

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Instalar dependencias
RUN apt update && apt install -y git

# Agregar las credenciales con variables de entorno
ARG GITHUB_TOKEN
ENV GITHUB_TOKEN=${GITHUB_TOKEN}

ARG REPO_NAME
ENV REPO_NAME=${REPO_NAME}

ARG REPO_OWNER
ENV REPO_OWNER=${REPO_OWNER}

RUN git clone https://${GITHUB_TOKEN}:x-oauth-basic@github.com/${REPO_OWNER}/${REPO_NAME}.git /app/${REPO_NAME}

# Copiar solo el archivo de requerimientos antes del resto del código
COPY requirements.txt /app/requirements.txt

# Instalar dependencias ANTES de copiar el resto de archivos
RUN pip install --no-cache-dir -r requirements.txt

# Copiar los archivos de la aplicación al contenedor
COPY . /app

# Exponer el puerto de la aplicación
EXPOSE 5000

ENV PYTHONUNBUFFERED=1

# Comando para ejecutar la aplicación
CMD ["python", "wiki_repo_webhook_server.py"]