services:
  wiki_chatbot:
    build:
      context: .
      dockerfile: Dockerfile.chatbot
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - REPO_OWNER=${REPO_OWNER}
        - REPO_NAME=${REPO_NAME}
        - CHATBOT_PORT=${CHATBOT_PORT}
        - WORKERS=${WORKERS}
    ports:
      - "${CHATBOT_PORT}:${CHATBOT_PORT}"
    environment:
      - CHATBOT_PORT=${CHATBOT_PORT}
      - REPO_NAME=${REPO_NAME}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - REPO_OWNER=${REPO_OWNER}
      - DB_PATH=${DB_PATH}
      - COLLECTION_NAME=${COLLECTION_NAME}
      - EMBEDDING_NAME=${EMBEDDING_NAME}
      - LLM_NAME=${LLM_NAME}
      - MAX_BATCH_SIZE=${MAX_BATCH_SIZE}
      - CHUNK_SIZE=${CHUNK_SIZE}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP}
      - PROMPT=${PROMPT}
      - WORKERS=${WORKERS}
    env_file:
      - ./chatbot/.env
    volumes:
      - ./chatbot:/app  # Monta el código de tu proyecto en el contenedor
      - ./chatbot/main.py:/app/main.py
    restart: unless-stopped